**1. Desarrollar un código en Jupyter Notebook que trabaje con arrays y realice varias operaciones
matemáticas y de manipulación de datos. El programa debe obtener la mediana, el promedio, y las
posiciones de los valores máximo y mínimo de un array. Además, deberá transformar el array en una
matriz y utilizar las funciones específicas para ello. A continuación se detalla los requerimientos:
(50 Pts)**

In [2]:
from numpy import array
from matplotlib.pylab import randint
from numpy import median
import numpy as np

**Crear un array de 10 elementos. Los elementos de este array deben ser consecutivos
del 1 al 10. Este array no debe ser aleatorio.**

In [3]:
arraigo = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) 
arraigo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Crear un segundo array de 10 elementos. Este array si debe ser aleatorio. Los valores
deben ser enteros entre el 1 al 20**

In [4]:
arraiglo = array([randint(1, 21) for _ in range(10)])
arraiglo

array([19, 11,  8,  5, 10,  4, 16,  7,  2,  2])

**Obtener un vector único de 10 elementos, sumando los dos arrays anteriores**

In [5]:
vector = arraigo + arraiglo

**Mezclar el vector obtenido en la letra C utilizando una función vista en la Unidad IV**

In [6]:
vector = np.random.permutation(vector)

**Calcular la Mediana, el Promedio y Posiciones de Valores Máximo y Mínimo utilizando
las funciones vistas en la Unidad IV. Tomar el vector de la letra D**

In [7]:
mediana = np.median(vector)

promedio = np.mean(vector)

maximo = np.max(vector)

minimo = np.min(vector)

**Transformar el vector obtenido en una Matriz de 2 x 5**

In [8]:
vector = np.reshape(vector, (2, 5))
vector

array([[13, 20, 15, 11, 10],
       [23, 11, 15, 12,  9]])